name: Deploy to Fly.io

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: Deploy to Fly
        run: flyctl deploy --remote-only --app frontend-old-dawn-5560
        working-directory: ./frontend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}